QCD:
  files:
    - /work/submit/lavezzo/SUEP/outputs/QCD_2018.root
  type:
    background
  color: 895
  
expected:
  files:
    - /work/submit/lavezzo/SUEP/outputs/predicted_data_2018.root
  type:
    data
  color: 895

data:
  files:
    - /work/submit/lavezzo/SUEP/outputs/predicted_data_2018.root
  type:
    data
  color: 895

SUEP-m1000-darkPhoHad:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m1000-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m1000-darkPho:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m1000-darkPho+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m1000-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m1000-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m125-darkPhoHad:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m125-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m125-darkPho:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m125-darkPho+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m125-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m125-generic-htcut+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-darkPhoHad:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal
SUEP-m400-darkPho:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-darkPho+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal
SUEP-m400-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md2-t0.5-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md2-t0.5-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md2-t1-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md2-t1-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md2-t2-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md2-t2-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md2-t3-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md2-t3-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md2-t4-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md2-t4-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md3-t1.5-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md3-t1.5-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md3-t3-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md3-t3-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md3-t6-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md3-t6-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md5-t10-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md5-t10-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md5-t1-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md5-t1-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m400-md5-t5-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m400-md5-t5-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m750-darkPhoHad:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m750-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m750-darkPho:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m750-darkPho+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

SUEP-m750-generic:
  files:
    - /work/submit/lavezzo/SUEP/outputs/SUEP-m750-generic+RunIIAutumn18-private+MINIAODSIM_sys_studies.root
  type:
    signal

