QCD:
  files:
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/GluGluToSUEP_HT400_T2p00_mS1000.000_mPhi8.000_T2.000_modehadronic_TuneCP5_13TeV_feb23_v2.root
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/QCD_2018.root
  type:
    background
  color: 895
  
expected:
  files:
    #- ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/QCD_2018.root
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/Data_2018.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018D-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
  type:
    data
  color: 895

data:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/Data_2018.root
    #- ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/QCD_2018.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018D-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
  type:
    data
  color: 895

GluGluToSUEP_HT400_T2p00_mS400.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig400_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS1000.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig1000_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS700.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig700_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS300.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig300_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS200.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig200_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS125.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig125_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS500.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig500_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS600.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig600_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS800.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig800_T2p00_phi2.000_2018.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS900.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig900_T2p00_phi2.000_2018.root
  type:
    signal

#GluGluToSUEP_HT400_T4p00_mS400.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig400_T4p00_phi2.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T4p00_mS1000.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig1000_T4p00_phi2.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T4p00_mS700.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig700_T4p00_phi2.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T4p00_mS300.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig300_T4p00_phi2.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T4p00_mS200.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig200_T4p00_phi2.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T4p00_mS125.000_mPhi2.00_T4.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig125_T4p00_phi2.000_2018.root
#  type:
#    signal
#
#GluGluToSUEP_HT400_T8p00_mS400.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig400_T8p00_phi4.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T8p00_mS1000.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig1000_T8p00_phi4.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T8p00_mS700.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig700_T8p00_phi4.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T8p00_mS300.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig300_T8p00_phi4.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T8p00_mS200.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig200_T8p00_phi4.000_2018.root
#  type:
#    signal
#GluGluToSUEP_HT400_T8p00_mS125.000_mPhi4.00_T8.000_modegeneric:
#  files:
#    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig125_T8p00_phi4.000_2018.root
