QCD:
  files:
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/GluGluToSUEP_HT400_T2p00_mS1000.000_mPhi8.000_T2.000_modehadronic_TuneCP5_13TeV_feb23_v2.root
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/QCD_2016.root
  type:
    background
  color: 895
  
expected:
  files:
    #- ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/QCD_2018.root
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/Data_2016.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018D-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
  type:
    data
  color: 895

data:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/Data_2016.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
    #- ~/nobackup/sueps/analysis/SUEPs/newlimits/CMSSW_10_2_13/src/SUEPLimits/offline_testfiles/JetHT+Run2018D-UL2018_MiniAODv2-v1+MINIAOD_feb23_v2.root
  type:
    data
  color: 895

GluGluToSUEP_HT400_T2p00_mS400.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig400_2016.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS1000.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig1000_2016.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS700.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig700_2016.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS300.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig300_2016.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS200.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig200_2016.root
  type:
    signal
GluGluToSUEP_HT400_T2p00_mS125.000_mPhi2.00_T2.000_modegeneric:
  files:
    - ~/nobackup/sueps/analysis/SUEPs/scouting/plotter/combineHist/sig125_2016.root
