era: 2016apv

WJHSdata:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016E-HIPM_UL2016_MiniAODv2-v5+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
  type:
    data
  color: 895

WJHSexpected:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016E-HIPM_UL2016_MiniAODv2-v5+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleElectron+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_18_data_limits_2016apv/SingleMuon+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
  type:
    data
  color: 895

GJHSdata:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016C-HIPM_UL2016_MiniAODv2-v4+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
  type:
    data
  color: 797

GJHSexpected:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016C-HIPM_UL2016_MiniAODv2-v4+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_VRGJ_11_20_limits_2016apv/SinglePhoton+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD.root
  type:
    data
  color: 797

SUEP_mS125.000_mPhi2.000_T0.500_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi2.000_T0.500_modegeneric.root
  sample: SUEP_mS125.000_mPhi2.000_T0.500_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi2.000_T1.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi2.000_T1.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi2.000_T1.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi2.000_T2.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi2.000_T2.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi2.000_T2.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi2.000_T4.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi2.000_T4.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi2.000_T4.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi2.000_T8.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi2.000_T8.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi2.000_T8.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi3.000_T0.750_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi3.000_T0.750_modegeneric.root
  sample: SUEP_mS125.000_mPhi3.000_T0.750_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi3.000_T1.500_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi3.000_T1.500_modegeneric.root
  sample: SUEP_mS125.000_mPhi3.000_T1.500_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi3.000_T12.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi3.000_T12.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi3.000_T12.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi3.000_T3.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi3.000_T3.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi3.000_T3.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi3.000_T6.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi3.000_T6.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi3.000_T6.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi4.000_T1.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi4.000_T1.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi4.000_T1.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi4.000_T16.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi4.000_T16.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi4.000_T16.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi4.000_T2.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi4.000_T2.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi4.000_T2.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi4.000_T4.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi4.000_T4.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi4.000_T4.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi4.000_T8.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi4.000_T8.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi4.000_T8.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi8.000_T16.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi8.000_T16.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi8.000_T16.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi8.000_T2.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi8.000_T2.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi8.000_T2.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi8.000_T32.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi8.000_T32.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi8.000_T32.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi8.000_T4.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi8.000_T4.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi8.000_T4.000_modegeneric
  type:
    signal

SUEP_mS125.000_mPhi8.000_T8.000_modegeneric:
  files:
    - /ceph/submit/data/user/l/lavezzo/SUEP/outputs//WH_11_24_signal_2016apv/SUEP_mS125.000_mPhi8.000_T8.000_modegeneric.root
  sample: SUEP_mS125.000_mPhi8.000_T8.000_modegeneric
  type:
    signal

